repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: check-ast
      language_version: python3.8
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml

- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
    - id: black
      language_version: python3.8
      exclude: ^api/gen/*
- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
    - id: bandit
      args: [-l, --recursive, -x, tests]
      files: ^(api|controllers)/.*\.py$

- repo: local
  hooks:
    - id: flake8
      # The provided hook fails to read config file. Therefore this wrapper.
      name: Python style checking
      entry: sh -c ".venv/bin/python -m flake8"
      language: system
    - id: safety
      name: Python vuln packages
      entry: sh -c ".venv/bin/python -m safety check"
      language: system
      files: poetry.lock
    - id: pytest
      name: Unit Tests
      entry: sh -c ".venv/bin/python -m pytest api/tests"
      language: system
