
services:
  dmss:
    build:
      context: .
    image: datamodelingtool.azurecr.io/dmss:latest
    restart: unless-stopped
    environment:
      ENVIRONMENT: azure
      REDIS_PASSWORD: maf
      AUTH_ENABLED: "True"
      SECRET_KEY: ${SECRET_KEY}
      AUTH_PROVIDER_FOR_ROLE_CHECK: AAD
    depends_on:
      - db
      - db_postgres
      - redis

  db:
    image: mongo:5.0.9
    command: mongod --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
    ports:
      - '27017:27017'

  db_postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dmss
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: maf
    ports:
      - '6379:6379'
      - '8001:8001'

volumes:
  db_data:
