version: "3.4"

services:
  nginx:
    build: ./nginx/local

  api:
    build:
      target: development
    volumes:
      - ./api/:/code
    environment:
      FLASK_DEBUG: 1
      ENVIRONMENT: local
      MONGO_AZURE_URI: ${MONGO_AZURE_URI}

  web:
    build:
      target: dev
    volumes:
      - ./web/src:/code/src
    environment:
      - NODE_ENV=development

  db-ui:
    depends_on:
      - db
    image: mongo-express:0.49
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: maf
      ME_CONFIG_MONGODB_ADMINPASSWORD: maf
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
