version: "3.8"

services:
  dmss:
    build:
      target: development
    image: dmss-dev
    volumes:
      - ./src:/code
      - ./.behaverc:/code/.behaverc
    environment:
      ENVIRONMENT: local
      LOGGING_LEVEL: debug
      MONGO_AZURE_URI: ${MONGO_AZURE_URI}
      AUTH_ENABLED: "False"
#      AUTH_ENABLED: "True"
      OAUTH_TOKEN_ENDPOINT: http://localhost:8080/auth/realms/dmss/protocol/openid-connect/token
      OAUTH_AUTH_ENDPOINT: http://localhost:8080/auth/realms/dmss/protocol/openid-connect/auth
      OAUTH_WELL_KNOWN: http://keycloak:8080/auth/realms/dmss/.well-known/openid-configuration
    ports:
      - "8000:5000"

#  keycloak:
#    image: quay.io/keycloak/keycloak:15.0.1
#    ports:
#      - "8080:8080"
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin

  db:
    image: mongo:3.4
    command: --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
    volumes:
      - ./data/db:/data/db


  db-ui:
    image: mongo-express:0.49
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: maf
      ME_CONFIG_MONGODB_ADMINPASSWORD: maf
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
