version: "3.4"

services:
  api:
    build:
      context: ./api
      target: development
    image: development
    volumes:
      - ./api/home:/code/home
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      ENVIRONMENT: local
      MONGO_INITDB_ROOT_PASSWORD: maf

  db:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: maf


