version: "3.8"

services:
  dmss:
    build:
      target: development
    image: dmss-dev
    volumes:
      - ./src:/code
      - ./.behaverc:/code/.behaverc
    environment:
      ENVIRONMENT: local
      MONGO_AZURE_URI: ${MONGO_AZURE_URI}
    ports:
      - "8000:5000"

  db:
    image: mongo:3.4
    command: --quiet
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
    volumes:
      - ./data:/data/db


  db-ui:
    image: mongo-express:0.49
    restart: unless-stopped
    ports:
      - "8082:8081"
    logging:
      driver: none
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: maf
      ME_CONFIG_MONGODB_ADMINPASSWORD: maf
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
