version: "3.4"

services:
  dmss:
    image: development
    build:
      context: .
      target: development
    environment:
      ENVIRONMENT: local
      MONGO_INITDB_ROOT_PASSWORD: maf

  db:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: maf


