version: "3.4"

services:
  mainapi:
    build:
      context: .
      target: development
    image: main-api
    volumes:
      - ./:/usr/src/app
    environment:
      FLASK_DEBUG: 1
      ENVIRONMENT: local
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
      APPLICATION_HOME: /usr/src/app/api/home
    ports:
      - "0.0.0.0:8000:5000"
    links:
      - maindb:db

  maindb:
    image: mongo:3.4
    command: --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf

  db-ui:
    depends_on:
      - maindb
    image: mongo-express:0.49
    ports:
      - "8082:8081"
    logging:
      driver: "none"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: maf
      ME_CONFIG_MONGODB_ADMINPASSWORD: maf
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    links:
      - maindb:db
