version: "3.4"

services:
  api:
    build:
      context: ./api
      target: development
    restart: unless-stopped
    volumes:
      - ./api/:/code
    environment:
      FLASK_DEBUG: 1
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
      MONGO_INITDB_DATABASE: maf
    ports:
      - "5000:5000"

  web:
    build:
      target: dev
    volumes:
      - ./web/src:/code/src
    environment:
      - NODE_ENV=development

  db:
    image: mongo:4.0.10
    command: --quiet
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
      MONGO_INITDB_DATABASE: maf

  db-ui:
    depends_on:
      - db
    image: mongo-express:0.49
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: maf
      ME_CONFIG_MONGODB_ADMINPASSWORD: maf
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

  nginx:
    build: ./nginx
    ports:
      - "80:80"

  oauth2:
    build:
      context: ./oauth-proxy
      target: local
    ports:
      - "8081:8081"
    environment:
      OAUTH2_PROXY_CLIENT_ID: 97a6b5bd-63fb-42c6-bb75-7e5de2394ba0
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_REDIRECT_URL: http://localhost/oauth2/callback
