version: "3.4"

services:
  dmss:
    build:
      context: .
    image: mariner.azurecr.io/dmss:latest
    restart: unless-stopped
    environment:
      ENVIRONMENT: azure
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
    depends_on:
      - db
  db:
    image: mongo:3.4
    command: --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf