version: '3.4'

services:
  api:
    build:
      context: ./api
      target: development
    entrypoint: ./wait-for-it.sh db 27017
    environment:
      FLASK_ENV: development
      ENVIRONMENT: azure
