version: "3.4"

services:
  mainapi:
    build:
      target: development
    image: main-api-dev
    volumes:
      - ./:/usr/src/app
    environment:
      FLASK_DEBUG: 1
      ENVIRONMENT: local
      MONGO_AZURE_URI: ${MONGO_AZURE_URI}
    ports:
      - "8000:5000"

  maindb:
    image: mongo:3.4
    command: --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
    volumes:
      - ./data/db:/data/db
    logging:
      driver: "none"

  db-ui:
    depends_on:
      - maindb
    image: mongo-express:0.49
    ports:
      - "8082:8081"
    logging:
      driver: "none"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: maf
      ME_CONFIG_MONGODB_ADMINPASSWORD: maf
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    links:
      - maindb:db
