apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: dmss
spec:
  environments:
    - name: prod
      build:
        from: release
    - name: dev
      build:
        from: master
  components:
    - name: api
      src: .
      ports:
        - name: flask
          port: 80
      publicPort: flask
      secrets:
        - MONGO_AZURE_URI
  dnsAppAlias:
    environment: prod
    component: api
