apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: data-modelling-tool
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
  components:
    - name: main
      src: "."
      publicPort: http
      ports:
        - name: http
          port: 80