apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: data-modelling-tool
spec:
  environments:
    - name: prod
      build:
        from: stable
    - name: dev
      build:
        from: master
    - name: features
      build:
        from: feature/*
  components:
    - name: api
      src: ./api
      ports:
        - name: flask
          port: 5000
      publicPort: flask
      secrets:
        - MONGO_AZURE_URI
    - name: oauth-proxy
      src: ./oauth-proxy
      ports:
        - name: nginx
          port: 8081
      publicPort: nginx
      secrets:
        - OAUTH2_PROXY_CLIENT_ID
        - OAUTH2_PROXY_CLIENT_SECRET
        - OAUTH2_REDIRECT_URL
  dnsAppAlias:
    environment: prod
    component: oauth-proxy
