openapi: 3.0.1
info:
  title: Data Modelling Storage Service API
  description: Data storage service for DMT
  version: 0.1.0

servers:
  - url: 'http://0.0.0.0:8000/api/v1'

tags:
  - name: package
    description: Packages
  - name: document
    description: Documents
  - name: explorer
    description: Virtual file system
  - name: datasource
    description: Data sources
paths:
  /data-sources:
    get:
      operationId: get_all
      x-openapi-router-controller: controllers.datasource_controller
      tags:
        - datasource
      summary: Get all data sources
      responses:
        '200':
          description: List of data sources
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /data-sources/{dataSourceId}:
    get:
      operationId: get_data_source
      x-openapi-router-controller: controllers.datasource_controller
      tags:
        - datasource
      summary: Get data source
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Data source
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  type:
                    type: string
                  documentType:
                    type: string
    post:
      operationId: save
      x-openapi-router-controller: controllers.datasource_controller
      tags:
        - datasource
      summary: Add data source
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/DocumentBody'
      responses:
        '200':
          description: Updated document
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    additionalProperties: true
  /packages/{dataSourceId}/findByName/{name}:
    get:
      operationId: find_by_name
      x-openapi-router-controller: controllers.package_controller
      tags:
        - package
      summary: Query packages
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: 'The name of the package to find'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Package
          content:
            application/json:
              schema:
                type: object
  /packages/{dataSourceId}:
    get:
      operationId: get
      x-openapi-router-controller: controllers.package_controller
      tags:
        - package
      summary: Get packages
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A document
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /documents/{dataSourceId}/{documentId}:
    get:
      operationId: get_by_id
      x-openapi-router-controller: controllers.document_controller
      tags:
        - document
      summary: Get document by ID
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
        - name: documentId
          in: path
          description: 'The document ID'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
    put:
      operationId: update
      x-openapi-router-controller: controllers.document_controller
      tags:
        - document
      summary: Update document
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
        - name: documentId
          in: path
          description: 'The document ID'
          required: true
          schema:
            type: string
        - name: attribute
          in: query
          description: 'Path to contained document'
          required: false
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/DocumentBody'
      responses:
        '200':
          description: Updated document
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    additionalProperties: true
  /documents-by-path/{dataSourceId}:
    get:
      operationId: get_by_path
      x-openapi-router-controller: controllers.document_controller
      tags:
        - document
      summary: Get document by path
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
        - name: path
          in: query
          description: 'The document path'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
  /explorer/{dataSourceId}/add-to-parent:
    post:
      operationId: add_to_parent
      x-openapi-router-controller: controllers.explorer_controller
      tags:
        - explorer
      summary: Add document to parent
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      requestBody:
        description: A JSON object containing document information
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                parentId:
                  type: string
                type:
                  type: string
                attribute:
                  type: string
              required:
                - name
                - parentId
                - type
                - attribute
      responses:
        '200':
          description: The UID of the added document
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
  /explorer/{dataSourceId}/add-to-path:
    post:
      operationId: add_to_path
      x-openapi-router-controller: controllers.explorer_controller
      tags:
        - explorer
      summary: Add document to path
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/DocumentBody'
      responses:
        '200':
          description: Added document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
  /explorer/{dataSourceId}/remove:
    post:
      operationId: remove
      x-openapi-router-controller: controllers.explorer_controller
      tags:
        - explorer
      summary: Remove document
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      requestBody:
        description: A JSON object containing document information
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parentId:
                  type: string
                  nullable: true
                documentId:
                  type: string
              required:
                - documentId
      responses:
        '200':
          description: Remove status
          content:
            application/json:
              schema:
                type: object
  /explorer/{dataSourceId}/move:
    put:
      operationId: move
      x-openapi-router-controller: controllers.explorer_controller
      tags:
        - explorer
      summary: Move document
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/DocumentBody'
      responses:
        '200':
          description: Added document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
  /explorer/{dataSourceId}/rename:
    put:
      operationId: rename
      x-openapi-router-controller: controllers.explorer_controller
      tags:
        - explorer
      summary: Rename document
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      requestBody:
        description: A JSON object containing rename information
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                parentId:
                  type: string
                  nullable: true
                description:
                  type: string
                  nullable: true
                documentId:
                  type: string
              required:
                - name
                - documentId
      responses:
        '200':
          description: Added document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
  /explorer/{dataSourceId}/add-package:
    post:
      operationId: add_package
      x-openapi-router-controller: controllers.explorer_controller
      tags:
        - explorer
      summary: Add package
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/DocumentBody'
      responses:
        '200':
          description: Added package
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
  /search/{dataSourceId}:
    post:
      operationId: search_entities
      x-openapi-router-controller: controllers.search_controller
      tags:
        - search
      summary: Search for entities
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      requestBody:
        description: A JSON object containing search parameters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  minLength: 5
              required:
                - type
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'

  /explorer/{dataSourceId}/add-document:
    post:
      operationId: add_document
      x-openapi-router-controller: controllers.explorer_controller
      tags:
        - explorer
      summary: Add document
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/DocumentBody'
      responses:
        '200':
          description: Added document UID
          content:
            application/json:
              schema:
                type: string
  /explorer/{dataSourceId}/add-raw:
    post:
      operationId: add_raw
      x-openapi-router-controller: controllers.explorer_controller
      tags:
        - explorer
      summary: Add raw document
      parameters:
        - name: dataSourceId
          in: path
          description: 'The data source ID'
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/DocumentBody'
      responses:
        '200':
          description: Added document UID
          content:
            application/json:
              schema:
                type: string
components:
  requestBodies:
    DocumentBody:
      required: true
      description: Object containing all info for a document
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DocumentBody'
  schemas:
    DocumentResponse:
      type: object
      additionalProperties:
        type: object
    DocumentBody:
      type: object
      additionalProperties: true
    SearchResponse:
      type: object
      additionalProperties: true
