version: "3.4"

services:
  mainapi:
    build: .
    image: main-api
    volumes:
      - ./:/usr/src/app
    environment:
      FLASK_DEBUG: 1
      ENVIRONMENT: local
    ports:
      - "8080:8080"
