name: Publish DMSS API to PyPI

on:
  push:
    branches:
      - master
    tags:
      - "**"

jobs:
  build-n-publish:
    name: Publish DMSS API to PyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install wheel and twine
        run: >-
          python -m
          pip install
          wheel
          twine
          --user
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Generate dmss-api
        working-directory: '.'
        env:
          API_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: ./generate-python-client.sh
      - name: Build a binary wheel and a source tarball
        working-directory: './gen/python'
        run: python3 setup.py sdist bdist_wheel
      - name: Publish gpa-api to PyPI
        working-directory: './gen/python'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        run: >-
          python -m
          twine upload
          dist/*
