name: Testing

on: [push]

jobs:
  testing:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: "Build Docker Images"
        run: docker-compose -f docker-compose.yml  -f docker-compose.ci.yml build
      - name: "BDD Tests"
        run: docker-compose -f docker-compose.yml  -f docker-compose.ci.yml run dmss behave
      - name: "Unit Tests"
        run: docker-compose -f docker-compose.yml  -f docker-compose.ci.yml run dmss pytest
