version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "./src:/code/src"
    environment:
      - NODE_ENV=development
    ports:
      - "80:3000"
